FROM public.ecr.aws/docker/library/python:3.12-slim-bullseye

# Install necessary system packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    simutrans-makeobj \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create function directory
RUN mkdir -p /var/task

# Install Python dependencies
RUN pip install --no-cache-dir \
    awslambdaric \
    requests_toolbelt

# Copy application files
COPY lambda-makeobj/* /var/task

WORKDIR /var/task

ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD [ "app.handler" ]
